### ISSUE TITLE
rats / viruses

### ISSUE THREAD

**Issue by rxvan** [avangersKinkyClient/KinkyClient-CSGO-Cheaters-Pack-dll-files#4]
i have only checked 3 of these however, they are ratted. fatality, gamesense and aimware all have viruses.

**Comment by avangersGameDestruction** [comment]
All programs got reverse engineered and cracked by me and other persons for checking if it is a rat or virus i can tell it hasn't it shows as a virus because it got a save option for your config and if it need it make a new folder and save your config inside that folder but the cheats themself are not viruses it not make a process in the background or it not make any customized mailware or rat or modified dll file in your system but if you don't trust it you not need to use them on your main driver. On your main computer you can always use a virtual machine if that machine got a virus on him just reboot it / reset it and your virtual machine is back clean and ready for use
